// Mocks generated by Mockito 5.4.0 from annotations
// in fitnesstracker/test/unit/workout/workout_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:fitnesstracker/domain/workouts/i_workout_repository.dart'
    as _i4;
import 'package:fitnesstracker/domain/workouts/workout_failures.dart' as _i6;
import 'package:fitnesstracker/infrastructure/workouts/workout_dto.dart' as _i3;
import 'package:fitnesstracker/infrastructure/workouts/workout_form_dto.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutDto_1 extends _i1.SmartFake implements _i3.WorkoutDto {
  _FakeWorkoutDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IWorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWorkoutRepository extends _i1.Mock
    implements _i4.IWorkoutRepository {
  MockIWorkoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.WorkoutDto>> getAllWorkout() => (super.noSuchMethod(
        Invocation.method(
          #getAllWorkout,
          [],
        ),
        returnValue: _i5.Future<List<_i3.WorkoutDto>>.value(<_i3.WorkoutDto>[]),
      ) as _i5.Future<List<_i3.WorkoutDto>>);
  @override
  _i5.Future<_i2.Either<_i6.WorkoutFailure, _i2.Unit>> create(
          _i7.WorkoutFormDto? workout) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [workout],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.WorkoutFailure, _i2.Unit>>.value(
            _FakeEither_0<_i6.WorkoutFailure, _i2.Unit>(
          this,
          Invocation.method(
            #create,
            [workout],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.WorkoutFailure, _i2.Unit>>);
  @override
  _i5.Future<_i2.Either<_i6.WorkoutFailure, _i2.Unit>> update(
          _i7.WorkoutFormDto? workout) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [workout],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.WorkoutFailure, _i2.Unit>>.value(
            _FakeEither_0<_i6.WorkoutFailure, _i2.Unit>(
          this,
          Invocation.method(
            #update,
            [workout],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.WorkoutFailure, _i2.Unit>>);
  @override
  _i5.Future<_i2.Either<_i6.WorkoutFailure, _i2.Unit>> delete(int? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [workoutId],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.WorkoutFailure, _i2.Unit>>.value(
            _FakeEither_0<_i6.WorkoutFailure, _i2.Unit>(
          this,
          Invocation.method(
            #delete,
            [workoutId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.WorkoutFailure, _i2.Unit>>);
  @override
  _i5.Future<_i3.WorkoutDto> getWorkout(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getWorkout,
          [id],
        ),
        returnValue: _i5.Future<_i3.WorkoutDto>.value(_FakeWorkoutDto_1(
          this,
          Invocation.method(
            #getWorkout,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.WorkoutDto>);
}
